#!/bin/bash

# This script customizes the look of the bash command prompt

# These color values can be overridden in ~/.bashrc
: ${preppy_usernameColor:=7}
: ${preppy_pathColor:=3}
: ${preppy_rootColor:=5}
: ${preppy_hostnameColor:=$preppy_usernameColor}
: ${preppy_atColor:=6}
: ${preppy_promptColor:=$preppy_atColor}
: ${preppy_promptSymbol:=❭}
: ${preppy_promptSymbol_root:=❱❱}

# TODO :move everything except the prompt character (and its coloring) to 'preppy-pc'.
# This way we can have 1 line above the prompt showing the following:
# gitinfo user@host|tmuxsessionname cwd
#
# . Put the display of every piece of info into a function:
#   v preppy_gitInfo
#   . preppy_userAtHost
#   v preppy_tmuxSessionName
#   . preppy_cwd
#
# . Move all functions to 'preppy' (simplifying 'preppy-pc')
#
# . Choose prompt character
#   i Some example Unicode characters (from http://shapecatcher.com/):
#
#       i Medium right-pointing angle bracket ornament
#           i Unicode: 0x276d
#           i Character: ❭
#
#       i Heavy right-pointing angle quotation mark ornament
#           i Unicode: 0x276f
#           i Character: ❯
#
#       i Heavy right-pointing angle bracket ornament
#           i Unicode: 0x2771
#           i Character: ❱
#
#       i Mathematical right double angle bracket
#           i Unicode: 0x27eb
#           i Character: ⟫
#

if [ "$EUID" -eq 0 ]; then

    # Prompt for root
    echo "$(fgpcolor $preppy_rootColor)\\u$(fgpcolor $preppy_atColor)@$(fgpcolor $preppy_hostnameColor)\\h$(tmuxSessionName) $(fgpcolor $preppy_pathColor)\\w $(fgpcolor $preppy_rootColor)${preppy_promptSymbol_root} $(fgp0)"

else

    # Prompt for non-root
    echo "$(fgpcolor $preppy_pathColor)\\w\n$(fgpcolor $preppy_usernameColor)\\u$(fgpcolor $preppy_atColor)@$(fgpcolor $preppy_hostnameColor)\\h$(tmuxSessionName) $(fgpcolor $preppy_promptColor)${preppy_promptSymbol} $(fgp0)"

fi
